name: tests
on:
  push:
    branches:
    - master
jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Install library
      run: make install
    - name: Verify code quality
      run: make quality
